Behaviors:
    Robot:
        Sensors:
            Cameras:
                Camera_0:
                    Name: 'camera_0'
                    Topic: '/carla/ego_vehicle/rgb_front/image'
                Camera_1:
                    Name: 'camera_1'
                    Topic: '/carla/ego_vehicle/rgb_view/image'
                Camera_2:
                    Name: 'camera_2'
                    Topic: '/carla/ego_vehicle/rgb_new/image'
                Camera_3:
                    Name: 'camera_3'
                    Topic: '/carla/ego_vehicle/dvs_front/image'
            Pose3D:
                Pose3D_0:
                    Name: 'pose3d_0'
                    Topic: '/carla/ego_vehicle/odometry'
            BirdEyeView:
                BirdEyeView_0:
                    Name: 'bird_eye_view_0'
                    Topic: ''
            Speedometer:
                Speedometer_0:
                    Name: 'speedometer_0'
                    Topic: '/carla/ego_vehicle/speedometer'
            wheel:
                wheel:
                    Name: 'wheel'
                    Topic: '/carla/ego_vehicle/steering_angle'
        BrainPath: [
#            'brains/CARLA/followlane/brain_carla_sb_sac.py',
#            'brains/CARLA/followlane/brain_carla_sb_sac_2.py',
#            'brains/CARLA/followlane/brain_carla_sb_sac_3.py', #just entropy gamma99
             'brains/CARLA/followlane/brain_carla_sb_sac_labeler.py',
 #           'brains/CARLA/followlane/brain_carla_sb_td3_2.py', # gamma99
#            'brains/CARLA/followlane/brain_carla_sb_td3_3.py', # gamma99
#            'brains/CARLA/followlane/brain_carla_sb_td3_4.py', # gamma99
#            'brains/CARLA/followlane/brain_carla_sb_ppo.py',
#            'brains/CARLA/followlane/brain_carla_sb_ppo_2.py',
#            'brains/CARLA/followlane/brain_carla_sb_ppo_3.py',
#            'brains/CARLA/followlane/brain_carla_sb_ppo_4.py',
#            'brains/CARLA/followlane/brain_carla_sb_ddpg.py',
#            'brains/CARLA/followlane/brain_carla_sb_ddpg_2.py',
#            'brains/CARLA/followlane/brain_carla_sb_ddpg_3.py',
#            'brains/CARLA/followlane/brain_carla_sb_ddpg_4.py',
#            'brains/CARLA/followlane/brain_carla_sb_sac_unbalanced.py',
#            'brains/CARLA/followlane/brain_carla_sb_ddpg_unbalanced.py',
#            'brains/CARLA/followlane/brain_carla_sb_ppo_unbalanced.py',
#            'brains/CARLA/followlane/brain_carla_sb_sac_04.py',
#            'brains/CARLA/followlane/brain_carla_sb_ppo_04.py',
#            'brains/CARLA/followlane/brain_carla_sb_ddpg_01.py',
#            'brains/CARLA/followlane/brain_carla_sb_sac_labeler.py',
#            'brains/CARLA/followlane/brain_carla_sb_sac_no_cc.py',
#            'brains/CARLA/followlane/brain_carla_sb_sac_no_speed.py',
#            'brains/CARLA/followlane/brain_carla_sb_ppo_01.py',
#            'brains/CARLA/followlane/brain_carla_sb_sac_no_01.py',
#            'brains/CARLA/followlane/brain_carla_sb_ppo_no_01.py',
            ]
        Actuators:
            CARLA_Motors:
                Motors_0:
                    Name: 'motors_0'
                    Topic: '/carla/ego_vehicle/vehicle_control_cmd'
                    MaxV: 3
                    MaxW: 0.3

        PilotTimeCycle: 50
        AsyncMode: True
        Parameters:
#            Model: ["sac_unbalanced", "ddpg_unbalanced", "ppo_unbalanced",
#            "sac_04", "ppo_04", "ddpg_01", "sac_01", "ppo_01", "sac_no_01", "ppo_no_01"]
#            Model: ["td3", "ddpg"]
            Model: ["sac"]
#            Model: ["sac_1", "sac_42", "sac_888", "sac_1234",
#               "td3_1", "td3_42", "td3_888", "td3_1234",
#               "ppo_1", "ppo_42", "ppo_888", "ppo_1234",
#               "ddpg_1", "ddpg_42", "ddpg_888", "ddpg_1234",
#            ]
#            Model: ["sac", "sac", "sac", "sac",
#               "td3", "td3", "td3", "td3",
#               "ppo", "ppo", "ppo", "ppo",
#               "ddpg", "ddpg", "ddpg", "ddpg",
#            ]
#            Model: ["sac", "td3", "ppo", "ddpg"]
            Config: []
#            Model: ["sac", "sac", "ddpg", "ddpg", "ddpg", "ddpg"]
            ImageCropped: True
            ImageSize: [ 100,50 ]
            ImageNormalized: True
            PredictionsNormalized: True
            GPU: True
            UseOptimized: True
            ImageTranform: ''
        Type: 'CARLA'
    Experiment:
        Name: "Experiment name"
        Description: "Experiment description"
        UseWorldTimeouts: False
        Timeout: [ 1 ] # time to poll if experiment is done (1 for each world)
        MaxWaits: [ 450 ] # maximum number of times the experiment status will be checked (MaxWaits * Timeout = max total time)
#        Timeout: [ 1, 1 ] # time to poll if experiment is done (1 for each world)
 #       MaxWaits: [ 450, 450 ] # maximum number of times the experiment status will be checked (MaxWaits * Timeout = max total time)
  #      Timeout: [1, 1, 1, 1, 1, 1] # time to poll if experiment is done (1 for each world)
  #      MaxWaits: [450, 450, 450, 450, 450, 450] # maximum stop
#        Timeout: [1, 1, 1, 1] # time to poll if experiment is done (1 for each world)
#        MaxWaits: [450, 450, 450, 450] # maximum number of times the experiment status will be checked (MaxWaits * Timeout = max total time)
        Repetitions: 1
        clientPort: 2000
    Simulation:
        World: [
      #       configs/CARLA/CARLA_launch_files/town_01_clockwise.launch,
      #       configs/CARLA/CARLA_launch_files/town_03_clockwise_ruben.launch,
             configs/CARLA/CARLA_launch_files/town_04_ruben.launch,
      #       configs/CARLA/CARLA_launch_files/town_02_clockwise.launch,
      #       configs/CARLA/CARLA_launch_files/town_06_clockwise_ruben.launch,
      #       configs/CARLA/CARLA_launch_files/town_10_clockwise_ruben.launch,
            ]
        RandomSpawnPoint: False
        SpawnPoints: []
    Dataset:
        In: '/tmp/my_bag.bag'
        Out: ''
    Stats:
        Out: './'
        PerfectLap: './perfect_bags/lap-simple-circuit.bag'
    Layout:
        Frame_0:
            Name: frame_0
            Geometry: [1, 1, 1, 1]
            Data: rgbimage
        Frame_1:
            Name: frame_1
            Geometry: [0, 1, 1, 1]
            Data: rgbimage
        Frame_2:
            Name: frame_2
            Geometry: [0, 2, 1, 1]
            Data: rgbimage
        Frame_3:
            Name: frame_3
            Geometry: [1, 2, 1, 1]
            Data: rgbimage
